# Generated by Django 3.1.3 on 2020-12-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201204_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Games', 'Games'), ('Food', 'Food2')], max_length=16),
        ),
    ]
