# Generated by Django 3.1.3 on 2020-12-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201204_2154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'item')},
        ),
    ]
